/* eslint-disable import/prefer-default-export */

export const SET_RUNTIME_VARIABLE = 'SET_RUNTIME_VARIABLE';
export const SET_LOCALE_START = 'SET_LOCALE_START';
export const SET_LOCALE_SUCCESS = 'SET_LOCALE_SUCCESS';
export const SET_LOCALE_ERROR = 'SET_LOCALE_ERROR';

// ************************
// собственные action types
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNOUT = 'SIGNOUT';
export const SET_NEXTPATH = 'SET_NEXTPATH';
export const SET_USER = 'SET_USER';
export const AXIOS_INITIAL = 'AXIOS_INITIAL';
export const AXIOS_REQUEST = 'AXIOS_REQUEST';
export const AXIOS_REQUEST_SUCCESS = 'AXIOS_REQUEST_SUCCESS';
export const AXIOS_REQUEST_FAIL = 'AXIOS_REQUEST_FAIL';
export const RICHTEXTEDITOR_ADD_DATA = 'RICHTEXTEDITOR_ADD_DATA';
export const RICHTEXTEDITOR_REMOVE_DATA = 'RICHTEXTEDITOR_REMOVE_DATA';
export const RICHTEXTEDITOR_UPDATE_PICTURES = 'RICHTEXTEDITOR_UPDATE_PICTURES';
export const RICHTEXTEDITOR_UPDATE_CONTENT = 'RICHTEXTEDITOR_UPDATE_CONTENT';
export const RICHTEXTEDITOR_SET_SUBMITTING = 'RICHTEXTEDITOR_SET_SUBMITTING';
export const RICHTEXTEDITOR_UPDATE_EDITORSTATE =
  'RICHTEXTEDITOR_UPDATE_EDITORSTATE';
export const RICHTEXTEDITOR_RESET_INITIAL = 'RICHTEXTEDITOR_RESET_INITIAL';

// ************************
