import _composeThingAddRoute from './composeThingAddRoute';
import _composeThingBackLinksRoute from './composeThingBackLinksRoute';
import _composeThingDBStatusRoute from './composeThingDBStatusRoute';
import _composeThingDeleteRoute from './composeThingDeleteRoute';
import _composeThingExportRoute from './composeThingExportRoute';
import _composeThingImportRoute from './composeThingImportRoute';
import _composeThingListRoute from './composeThingListRoute';
import _composeThingPreviewRoute from './composeThingPreviewRoute';
import _composeThingRecoverRoute from './composeThingRecoverRoute';
import _composeThingRichTextRoute from './composeThingRichTextRoute';
import _composeThingSearchFormsRoute from './composeThingSearchFormsRoute';
import _composeThingSearchRoute from './composeThingSearchRoute';
import _composeThingUpdateRoute from './composeThingUpdateRoute';

export const composeThingAddRoute = _composeThingAddRoute;
export const composeThingBackLinksRoute = _composeThingBackLinksRoute;
export const composeThingDBStatusRoute = _composeThingDBStatusRoute;
export const composeThingDeleteRoute = _composeThingDeleteRoute;
export const composeThingExportRoute = _composeThingExportRoute;
export const composeThingImportRoute = _composeThingImportRoute;
export const composeThingListRoute = _composeThingListRoute;
export const composeThingPreviewRoute = _composeThingPreviewRoute;
export const composeThingRecoverRoute = _composeThingRecoverRoute;
export const composeThingRichTextRoute = _composeThingRichTextRoute;
export const composeThingSearchFormsRoute = _composeThingSearchFormsRoute;
export const composeThingSearchRoute = _composeThingSearchRoute;
export const composeThingUpdateRoute = _composeThingUpdateRoute;
